# 1 워크플로의 이름 지정
name: CI/CD
on:                                  # Event 감지
  push:
    branches:
      - release

# 2 워크플로가 시작될 조건 지정
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3

      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install dependencies    # 의존 파일 설치
        run: npm install

      - name: Generate build          # React Build
        run: npm run build
